//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Xamarin.Forms.Xaml.XamlResourceIdAttribute("LinphoneXamarin.components.Groups.xaml", "components/Groups.xaml", typeof(global::LinphoneXamarin.components.Groups))]

namespace LinphoneXamarin.components {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("C:\\xamarian_touch\\LinphoneXamarin\\LinphoneXamarin\\components\\Groups.xaml")]
    public partial class Groups : global::Xamarin.Forms.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
        private global::LinphoneXamarin.components.userControllers.MySearch search;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(Groups));
            search = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::LinphoneXamarin.components.userControllers.MySearch>(this, "search");
        }
    }
}
